Django/abcd/abcd/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.http import HttpResponse
from iportfolio import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.iportfolio, name="top"),
    path("accounts/", include("accounts.urls")),
    path("iportfolio/", include("iportfolio.urls")),
    path("news/", include("news.urls")),
    path("shopping/", include("shopping.urls")),
    path("social_auth/", include("social_auth.urls")),
    path("drf/", include("drf.urls")),
    path("snippets/", include("snippets.urls")),
    path("__debug__/", include("debug_toolbar.urls")), # django-debug-toolbar
    # robots.txt
    re_path(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
]

if settings.SOCIAL_AUTH == True:
    urlpatterns += [
        # 以下を設定するだけで自分でルーティングの設定をすることなく、
        # django-allauthがデフォルトで設定している認証関係のページを利用できる 
        # ただ、login.html、signup.htmlなどをオーバーライドすることは可能
        # macにAnacondaをインストールしている自分の環境では以下の場所にtemplateは存在
        # /Users/$USER/opt/anaconda3/lib/python3.9/site-packages/allauth/templates/account
        path("social_auth/", include("allauth.urls")), # django-allauth
    ]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG: # DEBUG=Falseの場合は自動的に無効化される
    # MEDIA_URLとMEDIA_ROOTの関連付け
    # リクエストされたURLが/MEDIA_URLから始まる場合にMEDIA_ROOTからファイルを取得するよう設定
    # URLが/media/{$file_path}である場合に、MEDIA_ROOT/{$file_path}のファイルが取得されるようになる
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

from errors import views
# handler400 = "myapp.views.handler400" # Bad Request
# handler403 = "myapp.views.handler403" # Forbidden
handler404 = views.handler404 # Not Found
# handler500 = views.handler500 # Internal Server Error

Django/abcd/accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from accounts import views
from accounts.views import SignupView
from accounts.views import ProfEditView
from accounts.views import ProfImgEditView
from accounts.views import GoodByeView
from accounts.views import (
    QUserListView,
    QUserDetailView,
)

app_name = "accounts"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"), # as_view(): クラスベースビューを関数化する
    path("login/", auth_views.LoginView.as_view(
        redirect_authenticated_user=True, # settings.pyのLOGIN_REDIRECT_URLにリダイレクト
        template_name="accounts/login.html"
    ), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("profile/<int:user_id>/create/", views.profcreate, name="prof_create"),
    path("profile/<int:pk>/edit/", ProfEditView.as_view(), name="prof_edit"),
    # UpdataViewはURL変数名が'pk'や'slug'でないとErrorが発生する
    path("profile/<int:pk>/img_edit/", ProfImgEditView.as_view(), name="profimg_edit"),
    path("profile/<int:pk>/goodbye/", GoodByeView.as_view(), name="goodbye"),
    path("q_userlist/", QUserListView.as_view(), name="q_userlist"),
    path("q_userdetail/<int:pk>/", QUserDetailView.as_view(), name="q_userdetail"),
]

Django/abcd/drf/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'drf'

# Routerクラスを用いて、パスとViewSetを紐付ける
# Routerクラスをインスタンス化
default_router = routers.DefaultRouter()
# category/ にCategoryViewSetをルーティング
default_router.register("music_category", views.CategoryViewSet)
# item/ にItemViewSetをルーティング
default_router.register("music_item", views.ItemViewSet)

urlpatterns = [
	# Routerクラスを使用すると、簡潔に書ける
	# default_routerをincludeする
	path("api/", include(default_router.urls), name="drf_top"),
]

# https://127.0.0.1:8000/drf/api/ にアクセス
# https://127.0.0.1:8000/drf/api/rest_cateory/ にアクセス

# 外部からAPIにアクセスして、データを取得する場合
# https://127.0.0.1:8000/drf/api/item_format=json

Django/abcd/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model

# Application
from accounts.models import Profile
from accounts.models import ProfImage

MyUser = get_user_model()

class SignupForm(UserCreationForm):
	""" ユーザー登録 """
	class Meta:
		model = MyUser
		fields = ('email',)


class LoginForm(AuthenticationForm):
	pass


# 全角数字を半角数字に
num_to_hankaku = str.maketrans('ー０１２３４５６７８９', '-0123456789')

class ProfEditForm(forms.ModelForm):
	class Meta:
		model = Profile
		exclude = ('user', 'note',)
		# fields = "__all__"としてhidden属性にする場合
		# またはテンプレート内にて{{ form.field_name.as_hidden }}を指定する
		# widgets = {'user': forms.HiddenInput()}

	# clean_<fieldname>メソッドによるクリーニング（正規化）処理 P168
	def clean_zip_code(self):
		zip_code = self.cleaned_data['zip_code']
		return zip_code.translate(num_to_hankaku)

	def clean_phone(self):
		phone = self.cleaned_data['phone']
		return phone.translate(num_to_hankaku)

	# 複数のフィールドに適応させる処理はcleanメソッド内に記述
	# def clean(self):
	#	cleaned_data = super().clean()
	#	phone = cleaned_dat.get('email')
	#	data = self.serialized_data
	#	return data


class ProfImgEditForm(forms.ModelForm):
	class Meta:
		model = ProfImage
		exclude = ('user', 'note',)


class QUserListForm(forms.Form):
	""" ユーザー検索用フォーム """
	q = forms.CharField(label='検索', max_length=128, )

Django/abcd/accounts/views.py
# Django
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET
from django.views import View
from django.views.generic import ListView, FormView, DetailView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.decorators.http import require_safe, require_http_methods
from django.http import HttpResponseForbidden
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.edit import ModelFormMixin
from django.views.generic.edit import FormMixin
from django.db.models import Q, F
from django.db import transaction

# Application
from accounts.models import MyUser
from accounts.models import Profile
from accounts.models import ProfImage
from accounts.forms import SignupForm
from accounts.forms import ProfEditForm
from accounts.forms import ProfImgEditForm
from accounts.forms import QUserListForm


####################################################
###   ユーザー登録
####################################################

# @transaction.atomic
class SignupView(CreateView):
	""" Customizedユーザー登録ページ """
	template_name = 'accounts/signup.html'
	form_class = SignupForm

	# 全てのクラスベースビューにて使われる
	# クラスベースビューでGET時に呼び出されるメソッド
	def get_success_url(self):
		# > CreateView を使うとき、self.object にアクセスできます。
		# > これは作成されているオブジェクトです。
		# > オブジェクトがまだ作成されていない場合、値は None になります。
		return reverse("accounts:prof_create", kwargs={'user_id': self.object.pk})


@login_required
@require_http_methods(['POST', 'GET'])
# @transaction.atomic
def profcreate(request, user_id):
	""" profileをMyUserと紐づける """
	user = get_object_or_404(MyUser, pk=user_id) # MyUserのインスタンスを要求されるので

	if user_id != request.user.id:
		return HttpResponseForbidden('この編集は許可されていません。')

	if request.method == 'POST':
		profile_form = ProfEditForm(request.POST)
		profimg_form = ProfImgEditForm(request.POST, request.FILES)

		if profile_form.is_valid() and profile_form.is_valid():
			profile = profile_form.save(commit=False) # commit=Falseにしないとエラー
			profile.user = user # userと紐づける
			user.profile.save()

			profimage = profimg_form.save(commit=False)
			profimage.user = user
			user.profimage.save()

			return redirect("accounts:profile", user_id=user.pk)

	else:
		profile_form = ProfEditForm()
		profimg_form = ProfImgEditForm()

	template = "accounts/profcreate.html"
	context = {
		'profile_form': profile_form,
		'profimg_form': profimg_form,
	}
	return render(request, template, context)


####################################################
###   プロフィール画面
####################################################

@login_required
def profile(request, user_id):
	""" ユーザーのプロフィールページ """
	user = get_user_model()
	# 参照、逆参照でやっても可
	profile = get_object_or_404(Profile, user_id=user_id) # pkではない
	profimage = get_object_or_404(ProfImage, user_id=user_id)

	if user_id != request.user.id:
		return HttpResponseForbidden('この編集は許可されていません。')

	template = "accounts/profile.html"
	context = {
		'profile': profile,
		'profimage': profimage,
		'you': request.user,
	}
	return render(request, template, context)


####################################################
###   プロフィール情報編集
####################################################

class ProfEditView(LoginRequiredMixin, UpdateView): # ログイン必須
	""" プロフィールの変更 """
	template_name = "accounts/profedit.html"
	model = Profile
	form_class = ProfEditForm

	def form_valid(self, form):
		if self.request.user.id != self.kwargs['pk']: # urlパラメータ取得
			return HttpResponseForbidden('この編集は許可されていません。')
		return super().form_valid(form) # get_success_url()メソッドの戻り値にリダイレクト

	def form_invalid(self, form):
		return super().form_invalid(form)
	
	# フォームの送信に成功した場合のリダイレクト先を指定
	def get_success_url(self):
		return reverse("accounts:profile", kwargs={'user_id': self.request.user.id})

	# DetailViewやUpdateViewにて使われる
	# 返された値はテンプレート上で{{ object }}として受け取ることができる
	def get_object(self, **kwargs):
		obj = Profile.objects.get(user_id=self.kwargs['pk'])
		return obj

	# https://itc.tokyo/django/get-form-kwargs/
	# https://stackoverflow.com/questions/45712699/django-how-to-set-value-of-hidden-input-in-template
	# クラス内で設定しているform_classに値を渡す
	def get_form_kwargs(self, *args, **kwargs): # フォームに初期値を渡す
		kwags = super().get_form_kwargs(*args, **kwargs)
		# kwags["user"] = self.requst.user.id
		return kwags


decorators = [login_required,] # ログイン必須
@method_decorator(decorators, name='dispatch') # dispatchメソッドを指定
class ProfImgEditView(UpdateView): # FormViewだとsave()時にINSERT INTOになってしまう
	""" プロフィール画像の変更 """
	template_name = 'accounts/profimgedit.html'
	model = ProfImage
	form_class = ProfImgEditForm

	def form_valid(self, form):
		if self.request.user.id != self.kwargs['pk']: # urlパラメータ取得
			return HttpResponseForbidden('この編集は許可されていません。')
		return super().form_valid(form) # get_success_url()メソッドの戻り値にリダイレクト
	
	def form_invalid(self, form):
		return super().form_invalid(form)

	def get_success_url(self):
		# urlキーワード引数指定
		return reverse("accounts:profile", kwargs={'user_id': self.request.user.id}) 

	# DetailView, Updateiewにて使われる
	def get_object(self, **kwargs):
		obj = ProfImage.objects.get(user_id=self.kwargs['pk'])
		return obj

	# Formを使うクラスベースビューにて使われる
	# クラス内で設定しているform_classに値を渡す
	def get_form_kwargs(self, *args, **kwargs): # フォームに初期値を渡す
		kwags = super().get_form_kwargs(*args, **kwargs)
		return kwags


class OwnerOnly(UserPassesTestMixin): # または@user_passes_test
	""" ログインしたユーザーの情報を、自分自身のみが編集できるようにする """
	def test_func(self):
		""" Booleanを返す """
		user = self.request.user
		return user.pk == self.kwargs['pk']

	# def get_test_func(self):
		

####################################################
###   ユーザー削除
####################################################

# 本来ならis_active=Falseにするべきだが、ここはテストなので
decorators = [login_required,]
@method_decorator(decorators, name='dispatch')
# テンプレート内では{{ object }} 部分に削除対象のモデルが表示される
class GoodByeView(DeleteView):
	""" ユーザーの退会 """
	template_name = 'accounts/goodbye.html'
	model = MyUser
	success_url = reverse_lazy("top")


####################################################
###   ユーザー検索
####################################################

# フォームとリストを混合させるテスト。実際には関数ベースビューで書いた方が良いだろう
class QUserListView(FormMixin, ListView):
	""" 検索box ＆ ユーザーリスト """
	""" 検索はMyUserのemailフィールドでもProfileのnicknameフィールドでも出来るようにした """
	template_name = 'accounts/Q_userlist.html'
	# model = Profile
	form_class = QUserListForm
	success_url = reverse_lazy("accounts:q_userlist")
	context_object_name = 'user_list'

	# ListViewにて使用できる
	# テンプレート内で{{ object_list }}とすることで取得できる
	def get_queryset(self, **kwargs): # querysetはiterable
		# model=Profileの場合、Profile.objects.all() と同じ結果
		# queryset = super().get_queryset(**kwargs) 
		queryset = None # 最初に全てのユーザー情報が表示されてしまうので

		# FormMixinとListViewで２回get_queryset()が呼び出される
		# そして２回目にはrequest.POSTの内容が消えてしまうのでsessionを活用
		# (ListView, FormMixin)の順に入れ替えても駄目
		session_from_data = self.request.session.pop('q', None)
		if session_from_data is not None:
			# N+1問題対策として、事前に結合
			prof_join_user = Profile.objects.select_related('user').all() # テーブルを連結
			queryset = prof_join_user.filter(user_id__in = session_from_data)
		return queryset

	# HTMLテンプレートへ任意のContextを渡すメソッド
	# 引数のkwargsにはurls.pyで指定した名前付き正規表現のプレースホルダにマッチした内容が入る
	def get_context_data(self, **kwargs):
		# 既存のget_context_dataをコール
		context = super().get_context_data(**kwargs)
		# context.update({})
		return context

	def get(self, request, *args, **kwargs):
		self.object = None # 初期値がNone
		return super().get(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		self.object = None
		self.object_list = self.get_queryset()
		form = self.get_form()
		if form.is_valid():
			# QuerySetは該当するデータがない場合は、例外を発生させずに空のQuerySetオブジェクトを返す
			# QuerySetは遅延評価される
			search_email = MyUser.objects.filter(email__contains=form.cleaned_data['q']) # QuerySetが返る
			search_nickname = Profile.objects.filter(nickname__contains=form.cleaned_data['q'])
			email_ids = [se.id for se in search_email]
			nickname_ids = [sn.user_id for sn in search_nickname]
			ids = list(set(email_ids + nickname_ids))
			self.request.session['q'] = ids
			# または一気に、
			# q_query = Q(nickname__icontains=form.cleaned_data['q']) 
			#	| Q(user__email__icontains=form.cleaned_data['q'])
			# queryset = Profile.objects.filter(q_query)
			# として、self.request.session['q'] = querysetを渡す

			# Qオブジェクトをadd()でOR検索する場合
			# q = Q()
			# q.add(Q(nickname__icontains=form.cleaned_data['q']), Q.OR)
			# q.add(Q(user__email__icontains=form.cleaned_Data['q']), Q.OR)
			# queryset = Profile.objects.filter(q)

			return self.form_valid(form)
		else:
			return self.form_invalid(form)


class QUserDetailView(DetailView):
	""" ユーザー詳細 """
	template_name = 'accounts/Q_userdetail.html'
	model = Profile
	context_object_name = 'q_user'





# JOIN
# prof = Profile.objects.select_related('user').all()
# for p in prof: print(p.user.email)
# prof.filter(Q(nickname__contains="i"))
# pro2 = Profile.objects.get(nickname="iku") # getでなければ親要素へアクセスできない
# pro2.user
# pro2.user.email
# Profile.objects.filter(user__email__contains='harada') # field名であることに注意
# MyUser.objects.filter(profile__nickname__contains='王子', profile__prefecture='北海道')

Django/abcd/accounts/templates/accounts/Q_userdetail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block extraheader %}
	<title>検索されたユーザー詳細</title>
{% endblock %}

{% block main %}
<section id="Q_detail" class="">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<div class="">
					<picture class="text-center p-5">
						<source srcset="/media/{{ q_user.prof_image }}" class="img-fluid" alt="プロフ画像" />
						<img src="/media/prof/prof_img.png" class="img-fluid" alt="プロフ画像" />
					</picture>
				</div>
			</div>
			<div class="col-md-8">
				<table class="table">
					<tbody>
						<tr>
							<th scope="row">ニックネーム</th>
							<td>{{ q_user.nickname }}</td>
						</tr>
						<tr>
							<th scope="row">氏名</th>
							<td>{{ q_user.last_name }}  {{ q_user.first_name }}</td>
						</tr>
						<tr>
							<th scope="row">メールアドレス</th>
							<td>{{ q_user.email }}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</section>
{% endblock %}

Django/abcd/accounts/templates/accounts/Q_userlist.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block extraheader %}
	<title>検索されたユーザー一覧</title>
{% endblock %}

{% block main %}
<section id="Q_list" class="">
	<div class="container">
		<div class="row">
			<div id="searchbox" class="">
				<form method="post" class="">
					{% csrf_token %}
					{% bootstrap_form form %}
            		{% bootstrap_button button_type="submit" content="検索" %}
				</form>
			</div>
			<div class="">
				{% for u in user_list %}
					<p>★★★★★★★★★★★★★★★</p>
					<a href="{% url 'accounts:q_userdetail' pk=u.user_id %}" class="">
					<p>Email: {{ u.user.email }}</p>
					<p>Nickname: {{ u.nickname }}</p>
					</a>
					<p>★★★★★★★★★★★★★★★</p>
				{% endfor %}
			</div>
		</div>
	</div>
</section>
{% endblock %}

Django/abcd/accounts/templates/accounts/goodbye.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block extraheader %}
	<title>ユーザー退会</title>
{% endblock %}

{% block main %}
<div class="container">
	<div class="row">
		<div class="">
			<form method="post" class="">
				{% csrf_token %}
				<p>本当に退会しますか？</p>
				<input type="submit" value="退会" class="btn btn-light">
				<a href="{% url 'accounts:profile' user_id=request.user.id %}" class="btn btn-light">戻る</a>
			</form>
		</div>	
	</div>
</div>
{% endblock %}

Django/abcd/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block extraheader %}
    <title>S Gold | ログイン</title>
{% endblock %}

{% block main %}
<!-- Breadcrums -->
<div class="container">
    <div class="row">
        <div class="">
            <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '>';">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'top' %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Login</li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<section class="" id="">
<div class="container">
    <div class="row">
        <div class="">
            <h2>ログイン</h2>
            <form method="post" class="mb-3">
                {% csrf_token %}
                {% comment %}
                    LoginViewに対して現在のURLが格納されたnextパラメータを渡す
                    view内で
                    next=request.POST.get('next')
                    if next != 'None':
                        return redirect(to=next)
                    のようにしてリダイレクト先を変更したりできる
                {% endcomment %}
                <input type="hidden" name="next" value="{{ next }}" />
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="ログイン" %}
            </form>
            <p>会員登録は<a href="{% url 'accounts:signup' %}">こちら</a></p>
        </div>
    </div>
</div>
</section>
{% endblock %}

Django/abcd/accounts/templates/accounts/profcreate.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block extraheader %}
    <title>プロフィール登録</title>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <h2>プロフィール登録</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}" />
            {% bootstrap_form profile_form %}
            {% bootstrap_form profimg_form %}
            {% bootstrap_button button_type="submit" content="登録" %}
        </form>
    </div>
</div>
{% endblock %}

Django/abcd/accounts/templates/accounts/profedit.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block extraheader %}
    <title>プロフィール編集</title>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <h2>プロフィール編集</h2>
        <form method="post" class="">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}" />
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="登録" %}
        </form>
    </div>
</div>
{% endblock %}

Django/abcd/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block extraheader %}
    <title>S Gold | 会員登録</title>
{% endblock %}

{% block main %}
<!-- Breadcrums -->
<div class="container">
    <div class="row">
        <div class="">
            <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '>';">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'top' %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Signup</li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<section class="" id="">
    <div class="container" id="">
        <div class="row" id="">
            <div class="">
                <h2>会員登録</h2>
                <form method="post" class="mb-3">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}">
                    {% bootstrap_form form %}
                    {% bootstrap_button button_type="submit" content="登録" %}
                </form>
                <p>ログインは<a href="{% url 'accounts:login' %}">こちら</a></p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Django/abcd/accounts/templates/accounts/signupview.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block extraheader %}
    <title>会員登録</title>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <h2>会員登録</h2>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}" />
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="登録" %}
        </form>
    </div>
</div>
{% endblock %}