Django/abcd/abcd/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.http import HttpResponse
from iportfolio import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.iportfolio, name="top"),
    path("accounts/", include("accounts.urls")),
    path("iportfolio/", include("iportfolio.urls")),
    path("news/", include("news.urls")),
    path("shopping/", include("shopping.urls")),
    path("social_auth/", include("social_auth.urls")),
    path("drf/", include("drf.urls")),
    path("snippets/", include("snippets.urls")),
    path("__debug__/", include("debug_toolbar.urls")), # django-debug-toolbar
    # robots.txt
    re_path(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
]

if settings.SOCIAL_AUTH == True:
    urlpatterns += [
        # 以下を設定するだけで自分でルーティングの設定をすることなく、
        # django-allauthがデフォルトで設定している認証関係のページを利用できる 
        # ただ、login.html、signup.htmlなどをオーバーライドすることは可能
        # macにAnacondaをインストールしている自分の環境では以下の場所にtemplateは存在
        # /Users/$USER/opt/anaconda3/lib/python3.9/site-packages/allauth/templates/account
        path("social_auth/", include("allauth.urls")), # django-allauth
    ]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG: # DEBUG=Falseの場合は自動的に無効化される
    # MEDIA_URLとMEDIA_ROOTの関連付け
    # リクエストされたURLが/MEDIA_URLから始まる場合にMEDIA_ROOTからファイルを取得するよう設定
    # URLが/media/{$file_path}である場合に、MEDIA_ROOT/{$file_path}のファイルが取得されるようになる
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

from errors import views
# handler400 = "myapp.views.handler400" # Bad Request
# handler403 = "myapp.views.handler403" # Forbidden
handler404 = views.handler404 # Not Found
# handler500 = views.handler500 # Internal Server Error

Django/abcd/accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from accounts import views
from accounts.views import SignupView
from accounts.views import ProfEditView
from accounts.views import ProfImgEditView
from accounts.views import GoodByeView
from accounts.views import (
    QUserListView,
    QUserDetailView,
)

app_name = "accounts"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"), # as_view(): クラスベースビューを関数化する
    path("login/", auth_views.LoginView.as_view(
        redirect_authenticated_user=True, # settings.pyのLOGIN_REDIRECT_URLにリダイレクト
        template_name="accounts/login.html"
    ), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("profile/<int:user_id>/create/", views.profcreate, name="prof_create"),
    path("profile/<int:pk>/edit/", ProfEditView.as_view(), name="prof_edit"),
    # UpdataViewはURL変数名が'pk'や'slug'でないとErrorが発生する
    path("profile/<int:pk>/img_edit/", ProfImgEditView.as_view(), name="profimg_edit"),
    path("profile/<int:pk>/goodbye/", GoodByeView.as_view(), name="goodbye"),
    path("q_userlist/", QUserListView.as_view(), name="q_userlist"),
    path("q_userdetail/<int:pk>/", QUserDetailView.as_view(), name="q_userdetail"),
]

Django/abcd/drf/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'drf'

# Routerクラスを用いて、パスとViewSetを紐付ける
# Routerクラスをインスタンス化
default_router = routers.DefaultRouter()
# category/ にCategoryViewSetをルーティング
default_router.register("music_category", views.CategoryViewSet)
# item/ にItemViewSetをルーティング
default_router.register("music_item", views.ItemViewSet)

urlpatterns = [
	# Routerクラスを使用すると、簡潔に書ける
	# default_routerをincludeする
	path("api/", include(default_router.urls), name="drf_top"),
]

# https://127.0.0.1:8000/drf/api/ にアクセス
# https://127.0.0.1:8000/drf/api/rest_cateory/ にアクセス

# 外部からAPIにアクセスして、データを取得する場合
# https://127.0.0.1:8000/drf/api/item_format=json

Django/abcd/iportfolio/urls.py
# Django
from django.urls import path
from django.urls import re_path
# Application
from iportfolio import views

app_name = "iportfolio"

# 関数ベースビュー
urlpatterns = [
	path("", views.iportfolio, name="iportfolio"), # "/iportfolio/"
	path("contact_confirm/", views.contact_confirm, name="contact_confirm"),
	path("contact_complete/", views.contact_complete, name="contact_complete"),
]

# クラスベースビュー
urlpatterns += [ # as_view(): クラスベースビューを関数化する
	# path("", views.TopPageView.as_view(), name="iportfolio"), 
	# path("contact_confirm/", views.ContactConfirmView, name="contact_confirm"),
	# path("contact_complete/", views.ContactCompleteView, name="contact_complete"),
]

Django/abcd/news/urls.py
# Django
from django.urls import path
from django.urls import re_path
# Application
from news import views

app_name = "news"

# 関数ベースビュー
urlpatterns = []

# クラスベースビュー
urlpatterns += [ # as_view(): クラスベースビューを関数化する
	path("", views.NewslistView.as_view(), name="news_list"), # "/news/"
	path("<int:pk>/", views.NewsDetailView.as_view(), name="news_detail"),
	path("register/", views.NewsRegisterView.as_view(), name="news_register"),
	path("<int:pk>/edit/", views.NewsEditView.as_view(), name="news_edit"), 
	path("<int:pk>/delete/", views.NewsDeleteView.as_view(), name="news_delete"), 
]

Django/abcd/shopping/urls.py
# Django
from django.urls import path
from django.urls import re_path
# Application
from shopping import views

app_name = "shopping"

urlpatterns = [
	path("", views.ShoppingTopView.as_view(), name="shopping_top"), # "/shopping/"
	# path("item_detail/<int:pk>/", views.ItemDetailView.as_view(), name="item_detail"), 
	path("item_detail/<int:pk>/", views.item_detail, name="item_detail"), 
	path("item_register/", views.item_register, name="item_register"),
	path("item/<int:pk>/edit/", views.ItemEditView.as_view(), name="item_edit"),
	path("item/searched_item/", views.SearchedItemView.as_view(), name="searched_item"),
	path("cart/adding_cart/<uuid:uuid>/", views.AddingCartView.as_view(), name="adding_cart"),
	# path("cart/detail/<uuid:uuid>/", views.CartDetailView.as_view(), name="cart_detail"),
	path("cart/detail/<uuid:uuid>/", views.cart_detail, name="cart_detail"),
	path("cart/plus_item/<int:item_id>/", views.plus_cart_item, name="plus_item_id"),
	path("cart/minus_item/<int:item_id>/", views.minus_cart_item, name="minus_item_id"),
	path("cart/delete_item/<int:item_id>/", views.delete_cart_item, name="delete_cart_item"),
	path("payment/detail/<int:user_id>/", views.payment_detail, name="payment_detail"),
	path("order/history/<int:pk>/", views.OrderHistoryView.as_view(), name="order_history"),
]

Django/abcd/templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ja">
<!-- extends "base.html" -->

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="noindex, nofollow, noarchive" /> <!-- クローラー禁止 -->
    {# descriptionは120文字以内で、特に最初の40文字にこだわる #}
    <meta content="DjangoをテストするためのWebサイトです" name="description" />
    <meta content="Django, Python, JavaScript" name="keywords" />
    <meta property="og:site_name" content="S Gold" />
    <meta property="og:locale" content="ja_JP" />
    {# Twitter #}
    <meta content="summery" name="twitter:card" />
    <meta content="@twitter_account" name="twitter:site" />

    <!-- Favicons -->
    <link href="{% static 'main/image/icon/favicon.png' %}" type="image/png" rel="icon">
    <link href="{% static 'main/image/icon/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,600,600i,700,700i|Satisfy|Comic+Neue:300,300i,400,400i,700,700i" rel="stylesheet">

    <!-- css -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css"> <!-- Bootstrap Icons -->

    <!-- private css -->
    <!-- http://127.0.0.1:8000/static/myapp/css/style.css などで確認できる -->
    <!-- for PC -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}" media="screen">
    <!-- for printer -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/print.css' %}" media="print">
    {% block extraheader %}{% endblock %}
</head>

<body>
    <!-- header -->
    <header id="header" class="">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" id="navbar">
                <a class="navbar-brand" href="/">S-Gold</a> <!-- アプリケーションタイトル -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <spna>Menu</spna>
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <!-- data-bs-target(折りたたみ部) -->
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-md-0">
                        <li class="dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Django</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'iportfolio:iportfolio' %}">iPortfolio</a></li>
                                <li><a class="dropdown-item" href="{% url 'shopping:shopping_top' %}">Shopping Cart</a></li>
                                <li><a class="dropdown-item" href="{% url 'news:news_list' %}">News List</a></li>
                                <li><a class="dropdown-item" href="/social_auth/login/">OAuth</a></li>
                                <li><a class="dropdown-item" href="/api/">Rest Framework</a></li>
                            </ul>
                        </li>
                        <li class="dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">ML</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="">Kaggle</a></li>
                                <li><a class="dropdown-item" href=""></a>OpenCV</li>
                                <li><a class="dropdown-item" href=""></a></li>
                            </ul>
                        </li>
                        <li class="dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Program</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="">Algorithm</a></li>
                                <li><a class="dropdown-item" href="">Python</a></li>
                                <li><a class="dropdown-item" href="">OpneCV</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'iportfolio:iportfolio' %}#contact">Contact</a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

                    <!--    
                    <div class="">
                        <ul class="navbar-navs">
                            {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">ログアウト</a></li>
                            {% else %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">ログイン</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">会員登録</a></li>
                            {% endif %}
                        </ul>
                    </div>  -->

    <!-- main -->
    <main>
        {% bootstrap_messages %}
        {% block main %}{% endblock %}
    </main>


    <!-- footer -->
    <footer>
        
    </footer>

    <!-- JavaScript -->
    <script src=""></script>
    {% block JavaScript %}{% endblock %}

</body>

</html>