Django/abcd/abcd/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.http import HttpResponse
from iportfolio import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.iportfolio, name="top"),
    path("accounts/", include("accounts.urls")),
    path("iportfolio/", include("iportfolio.urls")),
    path("news/", include("news.urls")),
    path("shopping/", include("shopping.urls")),
    path("social_auth/", include("social_auth.urls")),
    path("drf/", include("drf.urls")),
    path("snippets/", include("snippets.urls")),
    path("__debug__/", include("debug_toolbar.urls")), # django-debug-toolbar
    # robots.txt
    re_path(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
]

if settings.SOCIAL_AUTH == True:
    urlpatterns += [
        # 以下を設定するだけで自分でルーティングの設定をすることなく、
        # django-allauthがデフォルトで設定している認証関係のページを利用できる 
        # ただ、login.html、signup.htmlなどをオーバーライドすることは可能
        # macにAnacondaをインストールしている自分の環境では以下の場所にtemplateは存在
        # /Users/$USER/opt/anaconda3/lib/python3.9/site-packages/allauth/templates/account
        path("social_auth/", include("allauth.urls")), # django-allauth
    ]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG: # DEBUG=Falseの場合は自動的に無効化される
    # MEDIA_URLとMEDIA_ROOTの関連付け
    # リクエストされたURLが/MEDIA_URLから始まる場合にMEDIA_ROOTからファイルを取得するよう設定
    # URLが/media/{$file_path}である場合に、MEDIA_ROOT/{$file_path}のファイルが取得されるようになる
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

from errors import views
# handler400 = "myapp.views.handler400" # Bad Request
# handler403 = "myapp.views.handler403" # Forbidden
handler404 = views.handler404 # Not Found
# handler500 = views.handler500 # Internal Server Error

Django/abcd/accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from accounts import views
from accounts.views import SignupView
from accounts.views import ProfEditView
from accounts.views import ProfImgEditView
from accounts.views import GoodByeView
from accounts.views import (
    QUserListView,
    QUserDetailView,
)

app_name = "accounts"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"), # as_view(): クラスベースビューを関数化する
    path("login/", auth_views.LoginView.as_view(
        redirect_authenticated_user=True, # settings.pyのLOGIN_REDIRECT_URLにリダイレクト
        template_name="accounts/login.html"
    ), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("profile/<int:user_id>/create/", views.profcreate, name="prof_create"),
    path("profile/<int:pk>/edit/", ProfEditView.as_view(), name="prof_edit"),
    # UpdataViewはURL変数名が'pk'や'slug'でないとErrorが発生する
    path("profile/<int:pk>/img_edit/", ProfImgEditView.as_view(), name="profimg_edit"),
    path("profile/<int:pk>/goodbye/", GoodByeView.as_view(), name="goodbye"),
    path("q_userlist/", QUserListView.as_view(), name="q_userlist"),
    path("q_userdetail/<int:pk>/", QUserDetailView.as_view(), name="q_userdetail"),
]

Django/abcd/drf/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'drf'

# Routerクラスを用いて、パスとViewSetを紐付ける
# Routerクラスをインスタンス化
default_router = routers.DefaultRouter()
# category/ にCategoryViewSetをルーティング
default_router.register("music_category", views.CategoryViewSet)
# item/ にItemViewSetをルーティング
default_router.register("music_item", views.ItemViewSet)

urlpatterns = [
	# Routerクラスを使用すると、簡潔に書ける
	# default_routerをincludeする
	path("api/", include(default_router.urls), name="drf_top"),
]

# https://127.0.0.1:8000/drf/api/ にアクセス
# https://127.0.0.1:8000/drf/api/rest_cateory/ にアクセス

# 外部からAPIにアクセスして、データを取得する場合
# https://127.0.0.1:8000/drf/api/item_format=json

Django/abcd/shopping/urls.py
# Django
from django.urls import path
from django.urls import re_path
# Application
from shopping import views

app_name = "shopping"

urlpatterns = [
	path("", views.ShoppingTopView.as_view(), name="shopping_top"), # "/shopping/"
	# path("item_detail/<int:pk>/", views.ItemDetailView.as_view(), name="item_detail"), 
	path("item_detail/<int:pk>/", views.item_detail, name="item_detail"), 
	path("item_register/", views.item_register, name="item_register"),
	path("item/<int:pk>/edit/", views.ItemEditView.as_view(), name="item_edit"),
	path("item/searched_item/", views.SearchedItemView.as_view(), name="searched_item"),
	path("cart/adding_cart/<uuid:uuid>/", views.AddingCartView.as_view(), name="adding_cart"),
	# path("cart/detail/<uuid:uuid>/", views.CartDetailView.as_view(), name="cart_detail"),
	path("cart/detail/<uuid:uuid>/", views.cart_detail, name="cart_detail"),
	path("cart/plus_item/<int:item_id>/", views.plus_cart_item, name="plus_item_id"),
	path("cart/minus_item/<int:item_id>/", views.minus_cart_item, name="minus_item_id"),
	path("cart/delete_item/<int:item_id>/", views.delete_cart_item, name="delete_cart_item"),
	path("payment/detail/<int:user_id>/", views.payment_detail, name="payment_detail"),
	path("order/history/<int:pk>/", views.OrderHistoryView.as_view(), name="order_history"),
]

Django/abcd/shopping/views.py
import uuid
import pytz # 好きなタイムゾーンに変更
from datetime import datetime
from urllib.parse import urlencode
from collections import deque # 先入れ先出し
from collections import OrderedDict # 値を追加した順序を記憶する事ができる辞書型風のデータ構造
# Django
from django.conf import settings
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic import FormView
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic.edit import ModelFormMixin
from django.views.generic.edit import FormMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.contrib import messages
from django.core.paginator import Paginator
from django.forms import formset_factory # 同じフォームを複数、同じ画面に表示させる
from django.core.mail import send_mail
from django.core.mail import EmailMessage # BCC
from django.template.loader import render_to_string # テンプレートを読み込む
from django.db.models import Prefetch
from django.db import transaction
from django.db import IntegrityError
from django.db import DatabaseError
from django.db.models import Func
from django.db.models import Value
from django.db.models import Subquery
from django.db.models import OuterRef
from django.utils import timezone


# Application
from shopping.models import (
	Item, ItemPhoto, ItemStock, ItemReview,
	G1, Foal, CartItem, Order, OrderDetail,
)
from shopping.forms import (
	ItemForm, G1Form, FoalForm, ItemPhotoForm,
	CartForm, ItemDeleteForm, PaymentForm, OrderHistoryForm, 
	ItemSearchForm, ItemReviewForm,
)

MyUser = get_user_model()

####################################################
###   Shopping Cart
####################################################

def initiate_shopping_session(request):
	""" SESSION['cart']を初期化 """
	if "cart" not in request.session:
		print('☆☆☆ SESSION["cart"]を初期化します ☆☆☆')
		
		###########################################
		#####           SESSION復習
		###########################################
		# https://freeheroblog.com/django-session/
		# 保存できる例：セッションはJSONのような型で指定する必要がある
		# とにかく深くするとダメ
		# request.session["sample"]くらいで抑えないと更新されない
		# [
		# 	{"username": "Tom"},
		#	{"age": "23"}
		# ]
		# 保存できない例：Pythonの辞書型、リストの内部の辞書型のバリューにリストを保存するような値は保存できない
		# [
		#	{"groupuser": ["Tom", "Chris", "Naomi"]},
		#	{"age": "23"}
		# ]
		# 辞書型ライクなセッションの保存のコード
		# request.session['session_array_data'] = dict(username="Micheal", age=26)
		# JSON復習
		# オブジェクトの場合は{"key": "value"}で囲み、配列の場合は[]で囲む。文字列は""で囲む

		# 識別用としてUUIDを作成するが、request.session.session_keyでも良いのかもしれない
		# cf) https://man.plustar.jp/django/topics/http/sessions.html
		# セッションスタート
		# if not request.session.session_key: request.session.create() 
		# セッションキー取得
		# session_key = request.session.session_key
		request.session["cart_uuid"] = uuid.uuid4()
		request.session["cart"] = {}
		request.session.set_expiry(60 * 30) # セッション期限/30分保持

	return None


class ShoppingTopView(FormMixin, ListView): 
	""" Shopping TopPage """
	# TODO: priceによる商品一覧の並び替えなど

	template_name = "shopping/shopping_top.html"
	model = Item
	context_object_name = "items"
	form_class = ItemSearchForm

	# ページにリクエストがきた際にそれをGETやPOSTに振り分ける処理のこと
	# つまり、dispatchは、getやpostの処理が呼ばれる前に呼ばれる処理
	def dispatch(self, request, *args, **kwargs):
		if "cart" not in request.session:
			# session["shopping"]を初期化
			initiate_shopping_session(request)
		return super().dispatch(request, *args, **kwargs)

	def get(self, request, *args, **kwargs):
		# self.searched_item = self.request.GET.get('searched_item')
		return super().get(request, *args, **kwargs) # 親のGETを呼び出す

	def post(self, request, *args, **kwargs):
		# self.object = self.get_object()
		form = self.get_form()
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		# テンプレート内ではitem.item_photo.filter(priority=1)のように出来ないので、
		# まずJOINしてからテンプレートで使う必要があった
		items = ItemPhoto.objects.select_related('item').filter(priority=1)
		context['items'] = items
		return context

	def get_queryset(self, **kwargs):
		queryset = super().get_queryset(**kwargs) # Item.objects.all()と同じ結果
		return queryset

	def form_valid(self, form):
		searched_item = form.cleaned_data['searched_item']
		# GETへのパラメーターを付与
		self.parameters = '?{}'.format(urlencode({'searched_item':searched_item}))
		return super().form_valid(form)
	
	def form_invalid(self, form):
		self.parameters = ''
		messages.add_message(self.request, messages.ERROR,
								"アイテムを検索できませんでした")
		return super().form_invalid(form)

	def get_success_url(self):
		redirect_url = reverse_lazy('shopping:searched_item')
		# parameters = urlencode({'start':self.start, 'end':self.end})
		# url = f'{redirect_url}?{parameters}'
		url_plus_params = '{}{}'.format(redirect_url, self.parameters)
		return url_plus_params


class SearchedItemView(FormMixin, ListView):
	""" アイテム検索の結果を表示するページ """
	template_name = "shopping/item/searched_item.html"
	model = Item
	context_object_name = "items"
	form_class = ItemSearchForm

	def dispatch(self, request, *args, **kwargs):
		if "cart" not in request.session:
			# session["shopping"]を初期化
			initiate_shopping_session(request)
		return super().dispatch(request, *args, **kwargs)

	def get(self, request, *args, **kwargs):
		if request.GET.get('searched_item', None):
			self.searched_item = request.GET.get('searched_item', None).split() # 空白で区切る
		else:
			self.searched_item = []
		return super().get(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		# self.object = self.get_object()
		form = self.get_form()
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context

	def get_queryset(self, **kwargs):
		""" ORを使用した、部分一致検索 """
		# OR検索
		q = Q()
		for key in self.searched_item:
			q.add(Q(name__icontains=key), Q.OR) # 大文字小文字を区別しない

		queryset = Item.objects.prefetch_related(
			Prefetch(
				'item_photo', # related_name
	        	queryset=ItemPhoto.objects.select_related('item').filter(priority=1), # query statement
    	    	to_attr='ipr', # name for reference
			),
		).filter(q)

		return queryset

	def form_valid(self, form):
		searched_item = form.cleaned_data['searched_item']
		# GETへのパラメーターを付与
		self.parameters = '?{}'.format(urlencode({'searched_item':searched_item}))
		return super().form_valid(form)
	
	def form_invalid(self, form):
		self.parameters = ''
		messages.add_message(self.request, messages.ERROR,
								"アイテムを検索できませんでした")
		return super().form_invalid(form)

	def get_success_url(self):
		redirect_url = reverse_lazy('shopping:searched_item')
		url_plus_params = '{}{}'.format(redirect_url, self.parameters)
		return url_plus_params


@require_http_methods(['GET', 'POST'])
def item_detail(request, pk): # クラスベースビューで作成したものはviews-sub.pyにて
	"""  """

	if "cart" not in request.session:
		# session["shopping"]を初期化
		initiate_shopping_session(request)

	##########################################################################
	#####     COOKIEセクション(SESSIONでも良いのだが、練習のためCOOKIEで)
	##########################################################################
	if 'checked_items' not in request.COOKIES:
		# COOKIE["checked_item"]を初期化
		print('☆☆☆ COOKIEの閲覧履歴を初期化します ☆☆☆')
		# Djangoでは仕様のためCOOKIEもSESSION同様配列を渡せない
		# PHPではsetcookie("buy[2]", "Video");のように配列を渡せるようだが...
		request.COOKIES['checked_items'] = ''

	# COOKIEが配列を格納できないため、閲覧したアイテムIDを文字列として格納させる（苦肉の策）
	# 本当は、閲覧した商品IDは全て保存し、DBに格納することが望ましいが、ここはテストなので４個で制限
	item_nums = deque(maxlen=4) # 先入れ先出し法
	for i in request.COOKIES.get('checked_items').split(','):
		item_nums.append(i) # maxlenを指定しているのでそれ以上は自動でpopleft()される

	if str(pk) not in item_nums: # 閲覧したアイテムがリストに含まれたいない場合
		if len(item_nums) >= 4: # 格納したアイテム数が4以上の時
			item_nums.popleft() # 枠を１つ開ける

		item_nums.append(str(pk)) # リストに格納
				
	checked_items = ','.join(item_nums) # 文字列として格納する
		
	# POST
	if request.method == 'POST':
		# cart_form
		if 'cart_form' in request.POST:
			cart_form = CartForm(request.POST or None)
			review_form = ItemReviewForm() # これをしていないとlocal variable 'review_form' referenced before assignment
			
			if cart_form.is_valid():
				# 同じ商品がクリックされた場合に、quantityの数をupdateする
				if request.session["cart"].get(str(pk)):
					request.session["cart"][str(pk)]["quantity"] += int(cart_form.cleaned_data['quantity'])
					if request.session["cart"][str(pk)]["stored"] == "yes": # CartItemテーブルに格納済みである場合
						request.session["cart"][str(pk)]["stored"] = "modified" # "modified"に変更
				# 初登録の場合
				else: 
					item_in_cart = {
						"item_id": pk,
						"quantity": int(cart_form.cleaned_data['quantity']),
						"stored": "no", # CartItemテーブルに格納時、"yes"に変更
					}
					request.session["cart"][str(pk)] = item_in_cart
			
				request.session["new_adding_item"] = pk
            
            	# messages.add_message(request, level, message)
				messages.add_message(request, messages.SUCCESS, "アイテムをカートに入れました")

				return redirect("shopping:adding_cart", uuid=request.session.get('cart_uuid'))
			else:
				messages.add_message(request, messages.ERROR, "アイテムをカートに入れられませんでした")

		# review_form
		if 'review_form' in request.POST:
			review_form = ItemReviewForm(request.POST or None)
			cart_form = CartForm() # これをしていないとlocal variable 'cart_form' referenced before assignment

Django/abcd/shopping/templates/shopping/include/breadcrums.html
<ul class="breadcrum"> <!-- olとの違い -->
    <li>Home</li>
    <li>parent page</li>
    <li>this page</li>
</ul>

Django/abcd/shopping/templates/shopping/include/login_and_cart.html
<div class="container">
	<div class="row">
		{# 右寄せ/横並び: https://www.tohoho-web.com/bootstrap5/utilities.html#flex_row_column #}
		<div class="d-flex justify-content-end">
			<ul class="d-flex flex-row">
				{% if request.user.is_authenticated %}
					{# Bootstrap5からはMargin Leftはms(start)となる #}
					<li class="ms-2">{{ user.email }}でログイン中</li>
				{# 元のページにリダイレクトさせる #}
					<li class="ms-2"><a href="{% url 'accounts:logout' %}?next="https://s-gold.net/shopping/">ログアウト</a></li>
				{% else %}
					{# 元のページにリダイレクトさせる #}
					<li class="ms-2"><a href="{% url 'accounts:login' %}?next={{ request.path }}">ログイン</a></li>
				{% endif %}
					<li class="ms-2"><a href="{% url 'shopping:cart_detail' uuid=request.session.cart_uuid %} ">カートを確認</a></li>
			</ul>
		</div>
	</div>
</div>

Django/abcd/shopping/templates/shopping/include/login_and_order_history.html
<div class="container">
	<div class="row">
		<div class="d-flex justify-content-end">
			<ul class="d-flex flex-row">
				{% if request.user.is_authenticated %}
					<li class="ms-2">{{ user.email }}でログイン中</li>
				{# 元のページにリダイレクトさせる #}
					<li class="ms-2"><a href="{% url 'accounts:logout' %}?next={{ request.path }}">ログアウト</a></li>
					<li class="ms-2"><a href="{% url 'shopping:order_history' pk=request.user.id %} ">注文履歴</a></li>
				{% else %}
				{# 元のページにリダイレクトさせる #}
					<li class="ms-2"><a href="{% url 'accounts:login' %}?next={{ request.path }}">ログイン</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</div>

Django/abcd/shopping/templates/shopping/include/pagination.html
    <div class="container" id="pagenation">
        <nav class="">
            <ul class="pagination d-flex justify-content-center">
                <!-- 前へ の部分 -->
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">&laquo;</a>
                    </li>
                {% endif %}

                {% if page_obj.has_previous %}
                    {% if page_obj.previous_page_number != 1 %}
                        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                        <li>…</li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}

                <!-- 現在ページ -->
                <li class="page-item active"><span class="page-link" href="#">{{ page_obj.number }}</span></li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                    {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                        <li>…</li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                    {% endif %}
                {% endif %}

                <!-- 次へ の部分 -->
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link disabled" href="#">&raquo;</a>
                    </li>
                {% endif %}

                {% comment %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number|add:'2' }}">{{ page_obj.next_page_number|add:'2' }}</a></li>
                {% endcomment %}
            </ul>
        </nav>
    </div>